### ISSUE TITLE
Error Occurs While Caching

### ISSUE THREAD

**Issue by BlueCat-de** [hustvl/DiffusionDrive#15]
Hi!
While I'm running navsim.planning.script.run_dataset_caching, the following error occurs:
```
[2024-12-20 10:47:32,918][__main__][INFO] - Global Seed set to 0
Seed set to 0
[2024-12-20 10:47:32,919][__main__][INFO] - Building Worker
[2024-12-20 10:47:33,246][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2024-12-20 10:47:33,247][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
Error executing job with overrides: ['agent=diffusiondrive_agent', 'experiment_name=training_diffusiondrive_agent', 'train_test_split=mini']
Traceback (most recent call last):
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/utils/multithreading/worker_ray_no_torch.py", line 125, in __init__
    super().__init__(self.initialize())
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/utils/multithreading/worker_ray_no_torch.py", line 137, in initialize
    return initialize_ray(
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/utils/multithreading/worker_ray_no_torch.py", line 78, in initialize_ray
    ray.init(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/worker.py", line 1633, in init
    bootstrap_address = services.canonicalize_bootstrap_address(address, _temp_dir)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/services.py", line 548, in canonicalize_bootstrap_address
    addr = get_ray_address_from_environment(addr, temp_dir)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/services.py", line 409, in get_ray_address_from_environment
    gcs_addrs = find_gcs_addresses()
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/services.py", line 380, in find_gcs_addresses
    return _find_address_from_flag("--gcs-address")
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/ray/_private/services.py", line 343, in _find_address_from_flag
    pids = psutil.pids()
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/psutil/__init__.py", line 1465, in pids
    _LOWEST_PID = ret[0]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/script/run_dataset_caching.py", line 99, in <module>
    main()
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/root/projects/E2E/DiffusionDrive/navsim/planning/script/run_dataset_caching.py", line 71, in main
    worker: WorkerPool = instantiate(cfg.worker)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 339, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/high_perf_store/surround-view/cqm/envs/diffusiondrive/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'navsim.planning.utils.multithreading.worker_ray_no_torch.RayDistributedNoTorch':
IndexError('list index out of range')
full_key: worker
```

**Comment by LegendBC** [comment]
Have you resolved this issue? I haven’t encountered this problem myself. Could you try caching the dataset using the official NAVSIM code? If that works, you can use the dataset cached by the NAVSIM official Transfuser baseline directly. There’s no difference in the data between DiffusionDrive and Transfuser.

**Comment by BlueCat-de** [comment]
Problem Solved.

**Comment by hey-cjj** [comment]
Hi @LegendBC @BlueCat-de, I found this process takes quite a long time but only outputs the following information.
`[2025-02-25 06:55:22,995][__main__][INFO] - Global Seed set to 0
Seed set to 0
[2025-02-25 06:55:23,010][__main__][INFO] - Building Worker
[2025-02-25 06:55:24,311][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-02-25 06:55:24,312][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
2025-02-25 06:55:27,500 INFO worker.py:1821 -- Started a local Ray instance.`
I'm not sure whether the process is going right and how long it should take.
